language: java

install:
  - export VERSION=6.3
  - export GRADLE_DIR=/tmp/gradle
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir ${GRADLE_DIR}
  - unzip -d ${GRADLE_DIR} gradle-${VERSION}-bin.zip
  - export PATH=${GRADLE_DIR}/gradle-${VERSION}/bin:$PATH
  - gradle -v

os:
  - linux
  - osx

jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

matrix:
  allow_failures:
    - os: osx
      jdk: openjdk8
    - jdk: openjdk15

  include:
    - name: Sonar
      os: linux
      jdk: openjdk11
      addons:
        sonarcloud:
          organization: "zialus-github"
          token:
            secure: "SXcx1ozWzEBka3oPqcFmZKDWgEzAJoFppzs5bWJ2eEBtlqAxSlcV30RNqfWHF9Togazo8M32SvRo1grSc1T3efxbp0lrC/8s9Xs1pS8AeOSWvyHnHc+b04DTyQUtBkcv8di92+5Eh15xj15w9FUCYUFvUgKoH+S0KEQvZQW3k39/fx2RR6HXQFq/10lxAVv8iwFLf2Rhsf9sp9l1HnVBNP4fA8TWIyIjhYBFkcexdEzgdZUZQzgjp/gEz/1ddFQHFYM1VkYDxWXOP7ZK6N2/Yicgcd0jc6XLUT91hyLPi1lMKJa6B3zos53wHhxOuF1zmgGy5472LB9oMT03jIYkutbj/gJ/Y5iOU92g01z144q3Gvf1jXoJ/tc51RCWhqMSY0pzY9o1S59Sk8LOBOGFRZ5+hSwkvo3PnkEnGP2IxErpEbf+jX9bw35x26vjnGLBzB7t5QlQ+MkJXlxSWuqL6izIF9JaY602F8NcXzTuCkN579qKSldPDP33bllDwF9xQLhBVLGYpocIjYgX7dmEK315Ww5ZQpffkK4tPgQb9qnnWMhDemKPZGI4yZmedTNbmjE9CHH1Q01YgPFnClsnQHWmH0jelTlLaMyxhUOFVB5VeBkeYV4X2Zbz2bgof6szgFM4DW7RTufazum5Kuxa3h/LXlxYmzAL1WimO6zvqK8="
      script: gradle sonarqube
