language: java

install:
  - export VERSION=6.8.3
  - export GRADLE_DIR=/tmp/gradle
  - wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip
  - mkdir ${GRADLE_DIR}
  - unzip -d ${GRADLE_DIR} gradle-${VERSION}-bin.zip
  - export PATH=${GRADLE_DIR}/gradle-${VERSION}/bin:$PATH
  - gradle -v

dist: xenial

os:
  - linux
  - osx

jdk:
  - openjdk16
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

jobs:
  allow_failures:
    - os: osx
      jdk: openjdk8
    - jdk: openjdk16

  include:
    - name: Sonar
      os: linux
      jdk: openjdk11
      addons:
        sonarcloud:
          organization: "zialus-github"
          token:
            secure: "i4A66tvlzV27KLOs3FRmOO02EKxRpswZieAlxL3DugfQrNQvbWMXs+ObNMus2eS/7dioDOMTJvSie+5yqobJo9cCg7VoXN2Are4ZJkHUcAOD/CqsCidpAUdzj5iBBz8fKZ+/sjWXHMiuqmeDDaZWKXIuQVUwLUhgfkUn8WhSXyujvIGUSya5hGY/4BYG0jV4OEmqZbawjerTgTPKthOX+kg2c7wUvLNyLf5lpvA2nW8fm+AE8t9UnxwJiGtLtEoT9Wdkpppo+mLU9aItl03qfdtnm9c+wWFhw7IGxZEOavw9Vv1rrP14zssyDNWEdh7lQnvDyBAFkvPkZfN2ylRVimxY95xshGdjG8ujGWfHmaDVKxQMQ13uYN+otvS8sTzAvz42ZZlWPTO+ZrPJh4cRoiWI5Fjxfu5Mgcp8Z7cnvGRt19E0/mE2sOEnSUat1p2ZqePUS7tzhqYrlMQsq46gqTpqe0FtDS4YR0JMyjVHv2GZxWgO7E16qWbJNbV2jFPp3vmrjFL639Q33Hx+aRCy2x3unIq1AXtJyESAkUdERZ0eYXvXyX+dwCcHkijB8wThwoCpPo14hPwgb2T+9NQhDka7AmRMR2LU0h1MChewzkQa0ZBe3iTEYQ7/osoghmsIl5tMlEQbDDwmigcvndQqGsq1g73CRoGqDKJTaz7/N8g="
      script:
        - gradle sonarqube
