language: java

install:
  - export VERSION=6.0-20190928230021+0000
  - wget https://services.gradle.org/distributions-snapshots/gradle-${VERSION}-bin.zip
  - mkdir /tmp/gradle
  - unzip -d /tmp/gradle gradle-${VERSION}-bin.zip
  - export PATH=/tmp/gradle/gradle-${VERSION}/bin:$PATH
  - gradle -v

os:
  - linux
  - osx

jdk:
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  
  - oraclejdk14
  - oraclejdk13
  - oraclejdk12
  - oraclejdk11
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: openjdk14
    - jdk: openjdk13
    - jdk: oraclejdk14
    - jdk: oraclejdk13
    - jdk: openjdk8