name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
        gradle-version: current
    - name: Gradle Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: pitest
        gradle-version: current
